services:
  app:
    build: .
    image: comfyui
    restart: on-failure
    command: ["python", "main.py", "--listen", "--normalvram"]
    ports:
      - "8188:8188"
    # environment:
    # - CUDA_LAUNCH_BLOCKING=1
    volumes:
      - ./input:/app/input
      - ./output:/app/output
      - ../models:/app/models
      - ../models/u2net:/root/.u2net
      - ./custom_nodes:/app/custom_nodes
      - ./user_settings:/app/user/default
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [compute, utility, gpu]
